# Generated by Django 4.2.7 on 2023-12-14 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pages", "0004_image_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="users/%Y/%m/%d/"
            ),
        ),
    ]
